# -*- coding: utf-8 -*-
map = []
map.append(('BBFBBFBBBBBBBBB BBBBBBBBBBBBB',
            'F                       q   B',
            'B  S       W                B',
            'F          W         d      B',
            'B          W BBBBBF         B',
            'F                           B',
            'B                           B',
            'B    B            WWWW      B',
            'B    B            |  B      B',
            'B    BBBBBF      WW-WWWWW   B',
            'B                          BB',
            'Bq             B            B',
            'B        d     B    d BBBB  B',
            'B              B            B',
            'B   BBB  WWWWWWWWWW         B',
            'B                           B',
            'B                        q  B',
            'B   d            d          B',
            'B                     B     B',
            'BBBBBBBBBB-BBBBBBBBBBBBBBBBBB',
            'B                           B',
            'B                           B',
            'B                       d   B',
            'B                           B',
            'B  q                        B',
            'B                        q  B',
            'B                           B',
            'B                d      q   B',
            'B  q       q                B',
            'B                           B',
            'B                           B',
            'B                           B',
            'B                           B',
            'B                           B',
            'B                           B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
            ))